name: interpolate-genetic-position-env
dependencies:
  - boost-cpp
  - git
  - gmp
  - zlib
# required for commitizen
  - nodejs
  - pre-commit
  - cppcheck
  - clang-format

  - libtool
  - automake
  - autoconf
  - make>=4.2
  - gxx_linux-64>=8.2.0
